kind: Service
apiVersion: v1
metadata:
  name: container
spec:
  selector:
    app: container
  ports:
    - port: 5001
  type: ClusterIP

---
kind: Service
apiVersion: v1
metadata:
  name: login
spec:
  selector:
    app: login
  ports:
    - port: 5002
  type: ClusterIP

---
kind: Service
apiVersion: v1
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - port: 5000
      nodePort: 30000
  type: NodePort