kind: Deployment
apiVersion: apps/v1
metadata:
  name: container
spec:
  selector:
    matchLabels:
      app: container
  replicas: 1
  template:
    metadata:
      labels:
        app: container
    spec:
      containers:
        - name: container
          image: lilliirnb/container:latest

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: login
spec:
  selector:
    matchLabels:
      app: login
  replicas: 1
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: lilliirnb/login:latest

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: lilliirnb/gateway:latest